apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssd
    app.kubernetes.io/managed-by: Helm
    chart: ssd-2025.02.00
    component: project-monitor
    heritage: Helm
    release: ssd
  name: project-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd
      component: project-monitor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-06-12T23:14:14+05:30"
      creationTimestamp: null
      labels:
        app: ssd
        chart: ssd-2025.02.00
        component: project-monitor
        heritage: Helm
        release: ssd
    spec:
      containers:
      - image: opsmx11/project-monitor:4d80376-23
        imagePullPolicy: IfNotPresent
        name: project-monitor
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/ssd-public-keys
          name: ssd-public-keys
        - mountPath: /app/secrets/
          name: ssdsecret
          readOnly: true
        - mountPath: /app/config/project-monitor.yaml
          name: project-monitor
          subPath: project-monitor.yaml
        - mountPath: /usr/local/share/ca-certificates
          name: custom-certs
        - mountPath: /app/secrets/project-monitor-token/
          name: token
          readOnly: true
        - mountPath: /app/app-config.yaml
          name: project-monitor-queue
          subPath: app-config.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ssdsecret
        secret:
          defaultMode: 420
          items:
          - key: AESEncryptionKey
            path: ssdsecret/AESEncryptionKey
          secretName: ssdsecret
      - name: project-monitor-queue
        secret:
          defaultMode: 420
          items:
          - key: app-config.yaml
            path: app-config.yaml
          secretName: project-monitor
      - configMap:
          defaultMode: 420
          name: ssd-proxy-certs
          optional: true
        name: ssd-proxy-certs
      - configMap:
          defaultMode: 420
          items:
          - key: ca.crt
            path: ca.crt
          name: customer-custon-ca
          optional: true
        name: custom-certs
      - configMap:
          defaultMode: 420
          name: ssd-public-keys
        name: ssd-public-keys
      - name: token
        secret:
          defaultMode: 420
          secretName: project-monitor-token
      - configMap:
          defaultMode: 420
          items:
          - key: project-monitor.yaml
            path: project-monitor.yaml
          name: project-monitor-config
        name: project-monitor
