apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssd
    app.kubernetes.io/managed-by: Helm
    chart: ssd-2025.02.00
    component: ssd-opa
    heritage: Helm
    release: ssd
  name: ssd-opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd
      component: ssd-opa
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ssd
        chart: ssd-2025.02.00
        component: ssd-opa
        heritage: Helm
        release: ssd
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: ssd-proxy-certs
            optional: true
        image: opsmx11/ssd-opa:a04a5c6-793
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 20
          httpGet:
            path: /health
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        name: ssd-opa
        ports:
        - containerPort: 8200
          protocol: TCP
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /health
            port: 8200
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/ssd-public-keys
          name: ssd-public-keys
        - mountPath: /app/secrets/
          name: ssdsecret
          readOnly: true
        - mountPath: /app/scanFiles
          name: scanfilepath
        - mountPath: /app/logs
          name: logs
        - mountPath: /app/config/ssd-opa.yaml
          name: ssd-opa-volume
          subPath: ssd-opa.yaml
        - mountPath: /usr/local/share/ca-certificates
          name: custom-certs
        - mountPath: /app/secrets/ssd-opa-token/
          name: token
          readOnly: true
      - args:
        - --config=/etc/otel/otel-sidecar-config.yaml
        image: otel/opentelemetry-collector-contrib:latest
        imagePullPolicy: Always
        name: otel-sidecar
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/otel
          name: otel-sidecar-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: ssd-public-keys
        name: ssd-public-keys
      - name: ssdsecret
        secret:
          defaultMode: 420
          items:
          - key: AESEncryptionKey
            path: ssdsecret/AESEncryptionKey
          secretName: ssdsecret
      - emptyDir: {}
        name: scanfilepath
      - emptyDir: {}
        name: logs
      - name: token
        secret:
          defaultMode: 420
          secretName: ssd-opa-token
      - name: ssd-opa-volume
        secret:
          defaultMode: 420
          items:
          - key: ssd-opa.yaml
            path: ssd-opa.yaml
          secretName: ssd-opa
      - configMap:
          defaultMode: 420
          name: ssd-proxy-certs
          optional: true
        name: ssd-proxy-certs
      - configMap:
          defaultMode: 420
          items:
          - key: ca.crt
            path: ca.crt
          name: customer-custon-ca
          optional: true
        name: custom-certs
      - configMap:
          defaultMode: 420
          name: otel-sidecar-config
        name: otel-sidecar-volume
