apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssd
    app.kubernetes.io/managed-by: Helm
    chart: ssd-2025.02.00
    component: token-machine
    heritage: Helm
    release: ssd
  name: token-machine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd
      component: token-machine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ssd
        chart: ssd-2025.02.00
        component: token-machine
        heritage: Helm
        release: ssd
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: opsmx11/token-machine:99eb752-36
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 60
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8050
          timeoutSeconds: 2
        name: token-machine
        ports:
        - containerPort: 8050
          protocol: TCP
        readinessProbe:
          failureThreshold: 60
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8050
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opsmx/config/
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: token-machine
      serviceAccountName: token-machine
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: token-machine
        name: config-volume
