apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: ssd
    meta.helm.sh/release-namespace: ssd-may
  creationTimestamp: "2025-06-12T15:46:16Z"
  generation: 14
  labels:
    app: ssd
    app.kubernetes.io/managed-by: Helm
    chart: ssd-2025.02.00
    component: toolchain
    heritage: Helm
    release: ssd
  name: tool-chain
  namespace: ssd-may
  resourceVersion: "18232730"
  uid: 53c336ee-aa32-4711-85c4-a73c2f4059e7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ssd
      component: toolchain
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-06-12T15:51:24Z"
      creationTimestamp: null
      labels:
        app: ssd
        component: toolchain
    spec:
      containers:
      - env:
        - name: GRAPHQL_URL
          value: http://dgraph-public:8080/graphql
        - name: TEMPORAL_HOSTPORT
          value: ssd-temporal-frontend:7233
        - name: S3_ENDPOINT_URL
          value: http://ssd-minio:9000/
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: accesskey
              name: ssd-minio
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: secretkey
              name: ssd-minio
        - name: Cypher_Key
          valueFrom:
            secretKeyRef:
              key: AESEncryptionKey
              name: ssdsecret
        - name: MOBSF_API_KEY
          valueFrom:
            secretKeyRef:
              key: mobsfapikey
              name: mobsf-secret
        envFrom:
        - configMapRef:
            name: ssd-proxy-certs
            optional: true
        image: opsmx11/tool-chain:300bf48-843
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /health
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: tool-chain
        ports:
        - containerPort: 8100
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /health
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tools/scanResult
          name: scanresult
        - mountPath: /tools/config/tool-chain.yaml
          name: tool-chain-volume
          subPath: tool-chain.yaml
        - mountPath: /tools/ssd-public-keys
          name: ssd-public-keys
        - mountPath: /tools/secrets/tool-chain
          name: token
          readOnly: true
        - mountPath: /usr/local/share/ca-certificates
          name: custom-certs
      - args:
        - --config=/etc/otel/otel-sidecar-config.yaml
        image: otel/opentelemetry-collector-contrib:latest
        imagePullPolicy: Always
        name: otel-sidecar
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/otel
          name: otel-sidecar-volume
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - |
          echo 'Waiting for TEMPORAL-FRONTEND to become ready...'
          until printf "." && nc -z -w 2 ssd-temporal-frontend 7233; do
             sleep 2;
          done;
          echo 'TEMPORAL-FRONTEND OK ✓'
        image: quay.io/opsmxpublic/pgchecker:v1
        imagePullPolicy: IfNotPresent
        name: temporalfrontend-check
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: scanresult
      - configMap:
          defaultMode: 420
          items:
          - key: tool-chain.yaml
            path: tool-chain.yaml
          name: tool-chain
        name: tool-chain-volume
      - configMap:
          defaultMode: 420
          name: ssd-proxy-certs
          optional: true
        name: ssd-proxy-certs
      - configMap:
          defaultMode: 420
          items:
          - key: ca.crt
            path: ca.crt
          name: customer-custon-ca
          optional: true
        name: custom-certs
      - name: token
        secret:
          defaultMode: 420
          optional: true
          secretName: tool-chain-token
      - configMap:
          defaultMode: 420
          name: ssd-public-keys
        name: ssd-public-keys
      - configMap:
          defaultMode: 420
          name: otel-sidecar-config
        name: otel-sidecar-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-06-12T15:46:20Z"
    lastUpdateTime: "2025-06-12T15:54:49Z"
    message: ReplicaSet "tool-chain-5bc97c4d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-13T04:02:33Z"
    lastUpdateTime: "2025-06-13T04:02:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 14
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
